// AUTO-GENERATED by src/bin/generate_ast.rs. Do not hand-edit.

use crate::token::Token;
use crate::value::Value;

pub type Object = Value;

#[derive(Debug, Clone)]
pub enum Expr {
    Assign {
        name: Token,
        value: Box<Expr>,
    },
    Binary {
        left: Box<Expr>,
        operator: Token,
        right: Box<Expr>,
    },
    Call {
        callee: Box<Expr>,
        paren: Token,
        arguments: Vec<Expr>,
    },
    Get {
        object: Box<Expr>,
        name: Token,
    },
    Grouping {
        expression: Box<Expr>,
    },
    Literal {
        value: Object,
    },
    Logical {
        left: Box<Expr>,
        operator: Token,
        right: Box<Expr>,
    },
    Set {
        object: Box<Expr>,
        name: Token,
        value: Box<Expr>,
    },
    Super {
        keyword: Token,
        method: Token,
    },
    This {
        keyword: Token,
    },
    Unary {
        operator: Token,
        right: Box<Expr>,
    },
    Variable {
        name: Token,
    },
}

pub trait ExprVisitor<R> {
    fn visit_assign_expr(&mut self, name: &Token, value: &Expr) -> R;
    fn visit_binary_expr(&mut self, left: &Expr, operator: &Token, right: &Expr) -> R;
    fn visit_call_expr(&mut self, callee: &Expr, paren: &Token, arguments: &Vec<Expr>) -> R;
    fn visit_get_expr(&mut self, object: &Expr, name: &Token) -> R;
    fn visit_grouping_expr(&mut self, expression: &Expr) -> R;
    fn visit_literal_expr(&mut self, value: &Object) -> R;
    fn visit_logical_expr(&mut self, left: &Expr, operator: &Token, right: &Expr) -> R;
    fn visit_set_expr(&mut self, object: &Expr, name: &Token, value: &Expr) -> R;
    fn visit_super_expr(&mut self, keyword: &Token, method: &Token) -> R;
    fn visit_this_expr(&mut self, keyword: &Token) -> R;
    fn visit_unary_expr(&mut self, operator: &Token, right: &Expr) -> R;
    fn visit_variable_expr(&mut self, name: &Token) -> R;
}

impl Expr {
    pub fn accept<R, V: ExprVisitor<R>>(&self, visitor: &mut V) -> R {
        match self {
            Expr::Assign { name, value } => visitor.visit_assign_expr(name, &**value),
            Expr::Binary {
                left,
                operator,
                right,
            } => visitor.visit_binary_expr(&**left, operator, &**right),
            Expr::Call {
                callee,
                paren,
                arguments,
            } => visitor.visit_call_expr(&**callee, paren, arguments),
            Expr::Get { object, name } => visitor.visit_get_expr(&**object, name),
            Expr::Grouping { expression } => visitor.visit_grouping_expr(&**expression),
            Expr::Literal { value } => visitor.visit_literal_expr(value),
            Expr::Logical {
                left,
                operator,
                right,
            } => visitor.visit_logical_expr(&**left, operator, &**right),
            Expr::Set {
                object,
                name,
                value,
            } => visitor.visit_set_expr(&**object, name, &**value),
            Expr::Super { keyword, method } => visitor.visit_super_expr(keyword, method),
            Expr::This { keyword } => visitor.visit_this_expr(keyword),
            Expr::Unary { operator, right } => visitor.visit_unary_expr(operator, &**right),
            Expr::Variable { name } => visitor.visit_variable_expr(name),
        }
    }
}
