// AUTO-GENERATED by src/bin/generate_ast.rs. Do not hand-edit.

use crate::token::Token;
use crate::value::Value;

pub type Object = Value;

#[derive(Debug, Clone)]
pub enum Stmt {
    Block {
        statements: Vec<Stmt>,
    },
    Class {
        name: Token,
        superclass: Box<Expr>,
        methods: Vec<Stmt>,
    },
    Expression {
        expression: Box<Expr>,
    },
    Function {
        name: Token,
        params: Vec<Token>,
        body: Vec<Stmt>,
    },
    If {
        condition: Box<Expr>,
        then_branch: Box<Stmt>,
        else_branch: Box<Stmt>,
    },
    Print {
        expression: Box<Expr>,
    },
    Return {
        keyword: Token,
        value: Box<Expr>,
    },
    Var {
        name: Token,
        initializer: Box<Expr>,
    },
    While {
        condition: Box<Expr>,
        body: Box<Stmt>,
    },
}

pub trait StmtVisitor<R> {
    fn visit_block_stmt(&mut self, statements: &Vec<Stmt>) -> R;
    fn visit_class_stmt(&mut self, name: &Token, superclass: &Expr, methods: &Vec<Stmt>) -> R;
    fn visit_expression_stmt(&mut self, expression: &Expr) -> R;
    fn visit_function_stmt(&mut self, name: &Token, params: &Vec<Token>, body: &Vec<Stmt>) -> R;
    fn visit_if_stmt(&mut self, condition: &Expr, then_branch: &Stmt, else_branch: &Stmt) -> R;
    fn visit_print_stmt(&mut self, expression: &Expr) -> R;
    fn visit_return_stmt(&mut self, keyword: &Token, value: &Expr) -> R;
    fn visit_var_stmt(&mut self, name: &Token, initializer: &Expr) -> R;
    fn visit_while_stmt(&mut self, condition: &Expr, body: &Stmt) -> R;
}

impl Stmt {
    pub fn accept<R, V: StmtVisitor<R>>(&self, visitor: &mut V) -> R {
        match self {
            Stmt::Block { statements } => visitor.visit_block_stmt(statements),
            Stmt::Class {
                name,
                superclass,
                methods,
            } => visitor.visit_class_stmt(name, &**superclass, methods),
            Stmt::Expression { expression } => visitor.visit_expression_stmt(&**expression),
            Stmt::Function { name, params, body } => {
                visitor.visit_function_stmt(name, params, body)
            }
            Stmt::If {
                condition,
                then_branch,
                else_branch,
            } => visitor.visit_if_stmt(&**condition, &**then_branch, &**else_branch),
            Stmt::Print { expression } => visitor.visit_print_stmt(&**expression),
            Stmt::Return { keyword, value } => visitor.visit_return_stmt(keyword, &**value),
            Stmt::Var { name, initializer } => visitor.visit_var_stmt(name, &**initializer),
            Stmt::While { condition, body } => visitor.visit_while_stmt(&**condition, &**body),
        }
    }
}
